services:
  redis:
    image: redis:6.2-alpine
    restart: always
    container_name: redis-app
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel debug --requirepass matteo
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local