import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Link from "next/link";
import Image from "next/image";
import LoginComponent from "@/components/LoginComponent";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="flex flex-col h-screen">
            <header className="flex justify-between items-center p-4">
              <nav className="flex flex-1 gap-4">
                <Link href="/">Home</Link>
                <Link href="/songs">Songs</Link>
                <Link href="/users">Users</Link>
              </nav>
              <div className="flex flex-1 justify-end">
                <LoginComponent />
              </div>
            </header>

            <main className="p-4 flex-1">{children}</main>

            <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center p-4">
              <a
                className="flex items-center gap-2 hover:underline hover:underline-offset-4"
                href="https://github.com/opac-teach/graphql"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  aria-hidden
                  src="/globe.svg"
                  alt="Globe icon"
                  width={16}
                  height={16}
                />
                Source code
              </a>
            </footer>
          </div>
        </body>
      </html>
    </Providers>
  );
}
