import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Link from "next/link";
import Image from "next/image";
import LoginComponent from "@/components/LoginComponent";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <Providers>
        <html lang="fr">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}>
        <div className="flex flex-col min-h-screen">

          <header className="border-b border-border">
            <div className="container mx-auto flex items-center justify-between p-4">
              <h1 className="text-2xl font-bold">Music App</h1>
              <nav className="flex space-x-2">
                <Button variant="ghost" size="sm" asChild>
                  <Link href="/">Accueil</Link>
                </Button>
                <Button variant="ghost" size="sm" asChild>
                  <Link href="/songs">Chansons</Link>
                </Button>
                <Button variant="ghost" size="sm" asChild>
                  <Link href="/users">Utilisateurs</Link>
                </Button>
                <Button variant="ghost" size="sm" asChild>
                  <Link href="/genres">Genres</Link>
                </Button>
                <LoginComponent />
              </nav>
            </div>
          </header>

          <main className="flex-1 container mx-auto p-4">
            {children}
          </main>

          <footer className="border-t border-border">
            <div className="container mx-auto p-4 text-center text-sm">
              <Link href="https://github.com/opac-teach/graphql" target="_blank" rel="noopener noreferrer" className="underline">
                Code source
              </Link>
            </div>
          </footer>
        </div>
        </body>
        </html>
      </Providers>
  );
}
